name: hangout
description: "Decisionly - Gamified Social Decision Making App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  confetti: ^0.8.0
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  flutter_staggered_animations: ^1.1.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
